# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-06 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_contribution_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='feedback',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='question',
            field=models.IntegerField(default=0),
        ),
    ]
