# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-08 19:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20171007_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='modified_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 8, 19, 33, 29, 685674, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
