# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-28 20:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_contest_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 28, 20, 46, 6, 317677, tzinfo=utc)),
        ),
    ]
