# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-28 21:02
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20171029_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), size=4),
        ),
    ]
