# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20170718_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Track'),
        ),
    ]
