# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 13:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20170727_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquizrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
